[project]
name = "agno-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.8.1",
    "fastapi>=0.116.1",
    "google-genai>=1.32.0",
    "sqlalchemy>=2.0.43",
    "yfinance>=0.2.65",
]
